on:
  workflow_call:
    inputs:
      semgrep_options:
        required: false
        type: string
        default: '--config auto --exclude Dockerfile'

jobs:
  semgrep:
    runs-on: [self-hosted, gke]

    container:
      # A Docker image with Semgrep installed. Do not change this.
      image: returntocorp/semgrep

    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

    steps:

      - name: 'Checkout Repo'
        uses: 'actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11' #v3.0.3

      - name: 'Static analysis'
        run: semgrep ci ${{ inputs.semgrep_options }}

  TruffleHog:
    runs-on: [self-hosted, gke]

    steps:
      - name: 'Checkout Repo'
        uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0

      - name: 'TruffleHog OSS'
        uses: 'trufflesecurity/trufflehog@main'
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

  Trivy:
    runs-on: [self-hosted, gke]

    steps:
      - name: 'Checkout Repo'
        uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0

      - name: 'Run Trivy vulnerability scanner in repo mode'
        uses: 'aquasecurity/trivy-action@0.20.0'
        with:
          scan-type: 'fs'
          scan-ref: '.'
          ignore-unfixed: true
          format: 'sarif'
